### ISSUE TITLE
Failed to start container caused by empty runc’s bundle directory

### ISSUE THREAD

**Issue by kei-yamazaki** [cloudfoundry/bpm-release#130] opened 2019-12-24 05:45 UTC
I’m using following bpm version.
```
# /var/vcap/packages/bpm/bin/bpm --version
1.1.6
```

Sometimes runc’s bundle directory becomes empty due to the restart of VM.
If the bundle directory is empty, the runc container will fail to start with the following logs (below is the case when gorouter failed to start).
```
# view /var/vcap/sys/log/gorouter/gorouter.stderr.log
…
time="2019-12-24T04:51:44Z" level=error msg="container with id exists: bpm-gorouter"
container with id exists: bpm-gorouter
```

And bpm’s logs.
```
# view /var/vcap/sys/log/gorouter/bpm.log
…
{"timestamp":"2019-12-24T04:48:14.421677214Z","level":"info","source":"bpm","message":"bpm.start.acquiring-lifecycle-lock.starting","data":{"job":"gorouter","process":"gorouter","session":"1.1"}}
{"timestamp":"2019-12-24T04:48:14.421800213Z","level":"info","source":"bpm","message":"bpm.start.acquiring-lifecycle-lock.complete","data":{"job":"gorouter","process":"gorouter","session":"1.1"}}
{"timestamp":"2019-12-24T04:48:14.421815013Z","level":"info","source":"bpm","message":"bpm.start.starting","data":{"job":"gorouter","process":"gorouter","session":"1"}}
{"timestamp":"2019-12-24T04:48:14.428102372Z","level":"info","source":"bpm","message":"bpm.start.start-process.starting","data":{"job":"gorouter","process":"gorouter","session":"1.2"}}
{"timestamp":"2019-12-24T04:48:14.428168571Z","level":"info","source":"bpm","message":"bpm.start.start-process.creating-job-prerequisites","data":{"job":"gorouter","process":"gorouter","session":"1.2"}}
{"timestamp":"2019-12-24T04:48:14.428236971Z","level":"info","source":"bpm","message":"bpm.start.start-process.building-spec","data":{"job":"gorouter","process":"gorouter","session":"1.2"}}
{"timestamp":"2019-12-24T04:48:14.428424569Z","level":"info","source":"bpm","message":"bpm.start.start-process.creating-bundle","data":{"job":"gorouter","process":"gorouter","session":"1.2"}}
{"timestamp":"2019-12-24T04:48:14.441473284Z","level":"info","source":"bpm","message":"bpm.start.start-process.running-container","data":{"job":"gorouter","process":"gorouter","session":"1.2"}}
{"timestamp":"2019-12-24T04:48:14.450426525Z","level":"info","source":"bpm","message":"bpm.start.start-process.complete","data":{"job":"gorouter","process":"gorouter","session":"1.2"}}
{"timestamp":"2019-12-24T04:48:14.450501924Z","level":"error","source":"bpm","message":"bpm.start.failed-to-start","data":{"error":"exit status 1","job":"gorouter","process":"gorouter","session":"1"}}
{"timestamp":"2019-12-24T04:48:14.450522124Z","level":"info","source":"bpm","message":"bpm.start.complete","data":{"job":"gorouter","process":"gorouter","session":"1"}}
```

state.json is gone.
```
# ls -al /var/vcap/data/bpm/runc/bpm-gorouter/
total 8
drwx--x--x 2 root root 4096 Dec 23 07:53 .
drwx------ 7 root root 4096 Dec 23 23:49 ..
```

In this state, of course, the runc list also fails.
```
# /var/vcap/packages/bpm/bin/runc --root /var/vcap/data/bpm/runc list
load container bpm-gorouter: container "bpm-gorouter" does not exist
ID                          PID         STATUS      BUNDLE                                                                   CREATED                          OWNER
bpm-loggr-forwarder-agent   1664        running     /var/vcap/data/bpm/bundles/loggr-forwarder-agent/loggr-forwarder-agent   2019-12-23T23:49:05.697471539Z   root
bpm-loggr-udp-forwarder     1395        running     /var/vcap/data/bpm/bundles/loggr-udp-forwarder/loggr-udp-forwarder       2019-12-23T23:49:03.569510683Z   root
bpm-loggregator_agent       1590        running     /var/vcap/data/bpm/bundles/loggregator_agent/loggregator_agent           2019-12-23T23:49:04.85133271Z    root
bpm-prom_scraper            1738        running     /var/vcap/data/bpm/bundles/prom_scraper/prom_scraper                     2019-12-23T23:49:06.746444399Z   root ```
```

[This commit](https://github.com/cloudfoundry/bpm-release/commit/ab9293b93ec1fa16404b482c852f9163e56f5a3e) has been fixed in the past, [reporting a container startup failure due to broken state.json](https://github.com/cloudfoundry/bpm-release/issues/123).

if the bundle directory is empty, I think additional processing to clean up the directory will be necessary.

**Comment by chenweienn** [comment] 2020-01-14 12:33
Hit same issue in Pivotal support case 230128 (PAS 2.5.17, bpm 1.1.1, garden-runc  v1.19.8,  runc 1.0.0-rc9).
I reproduce in my lab.

- monit stop  @loggregator_agent
- mkdir -p /var/vcap/data/bpm/runc/bpm\-loggregator_agent
- monit start loggregator_agent

Previous [#fix](https://github.com/cloudfoundry/bpm-release/commit/ab9293b93ec1fa16404b482c852f9163e56f5a3e) cleaned up state.json, but runc also check its [parent path](https://github.com/opencontainers/runc/blob/v1.0.0-rc9/libcontainer/factory_linux.go#L202-L203).

Thanks.

**Comment by professor** [comment] 2020-02-21 18:43
We're running into this same issue in PKS. When a VM is shutdown without telling bosh, we've seen this issue happen as the VM comes back online. 

We deploy PKS API. We restart PKS API unannounced by sshing to each node and issue a VM `shutdown -r +0`. Bosh resurrector sees that the VM is down and restarts it. When this happens, we are in this state.

**Comment by xoebus** [comment] 2020-02-27 18:46
Hey there,

I took a step back from #140 and decided to fix the root cause in https://github.com/cloudfoundry/bpm-release/commit/7b88cee17a8ebd75feaf504a262cb27826f3c08d.

Would any of you be able to build a dev release from this commit and confirm that it fixes the issue that you're seeing?

Thanks!

**Comment by xoebus** [comment] 2020-03-23 00:01
Confirmed fixed in Slack!

**Closed** 2020-03-23 00:01 UTC
Labels: unscheduled
